benegifts/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    include,
    path
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop import views

app_name = "shop"


urlpatterns = [
    path("", views.index, name="index"),
    path("benedict/", views.benedict, name="benedict"),
    path("benetex/", views.benetex, name="benetex"),
    path("logo-lay-on/", views.logo_lay_on, name="logo_lay_on"),
    path("category/<slug:slug>/", views.category_detail, name="category"),
    path("product/<slug:slug>/", views.product_detail, name="product"),
    path("news/<slug:slug>/", views.news_detail, name="news"),
    path("form/<str:type>/", views.form, name="form"),
]

shop/models.py
from django.db import models


class Category(models.Model):

    parent_category = models.ForeignKey("self", on_delete=models.CASCADE, related_name="sub_categories", blank=True, null=True, verbose_name="Категория")
    name = models.CharField(verbose_name="Имя категории", max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(verbose_name="Фото", upload_to="categories/", blank=True, null=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return f"{self.parent_category} ({self.name})" if self.parent_category is not None else self.name
    
    @property
    def sub_category_first(self):
        return self.sub_categories.order_by("id").first()


class Product(models.Model):

    name = models.CharField(max_length=200, verbose_name="Имя товара")
    category = models.ManyToManyField(Category, related_name="products", verbose_name="Категория")
    image = models.ImageField(verbose_name="Фото", upload_to='products/')
    slug = models.SlugField(max_length=200, unique=True)
    size = models.CharField(verbose_name="Размеры", max_length=150)
    material = models.CharField(verbose_name="Материал", max_length=150)
    weight = models.CharField(verbose_name="Вес", max_length=20)
    price = models.CharField(verbose_name="Цена", max_length=20)
    description = models.TextField(verbose_name="Описание")
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты" 

    def __str__(self):
        return f"{', '.join(str(cat_ry) for cat_ry in self.category.all())} - {self.name}"
    
    def product_colors_by_three(self):
        product_colors = self.product_colors.all()
        return [product_colors[i : i + 3] for i in range(0, product_colors.count(), 3)]


class ProductImage(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_images', verbose_name="Продукт")
    image = models.ImageField(verbose_name="Фото", upload_to="products_images/")

    class Meta:
        db_table = "shop_product_image"
        ordering = ("product__name",)
        verbose_name = "Фото продукта"
        verbose_name_plural = "Фото продуктов" 

    def __str__(self):
        return str(self.product)


class ProductColor(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_colors", verbose_name="Продукт")
    color = models.CharField(verbose_name="Цвет", max_length=50)

    class Meta:
        db_table = "shop_product_color"
        ordering = ("product__name",)
        verbose_name = "Цвет продукта"
        verbose_name_plural = "Цвета продуктов" 

    def __str__(self):
        return str(self.product)


class News(models.Model):

    name = models.CharField(verbose_name="Имя новости", max_length=200)
    description = models.CharField(verbose_name="Описание", max_length=500)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(verbose_name="Фото", upload_to="news/")
    content = models.TextField(verbose_name="Текст новости")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-id",)
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
    
    def __str__(self) -> str:
        return self.name


class LogoLayOn(models.Model):

    name = models.CharField(verbose_name="Имя нанесения логотипа", max_length=50)
    image_1 = models.ImageField(verbose_name="Фото нанесения 1", upload_to="logo-lay-ons/")
    image_2 = models.ImageField(verbose_name="Фото нанесения 2", upload_to="logo-lay-ons/")
    image_3 = models.ImageField(verbose_name="Фото нанесения 3", upload_to="logo-lay-ons/")
    image_4 = models.ImageField(verbose_name="Фото нанесения 4", upload_to="logo-lay-ons/")
    video = models.FileField(verbose_name="Видео", upload_to="logo-lay-ons/videos/")

    class Meta:
        db_table = "shop_logo_lay_on"
        ordering = ("id",)
        verbose_name = "Нанесение логотипа"
        verbose_name_plural = "Нанесения логотипа"
    
    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    
    class ContactType(models.TextChoices):
        CALL_ORDER = "call-order", "Звонок на заказ"
        PRODUCT_ORDER = "product-order", "Заказ продукта"
        DEALER = "dealer", "Дилер"
        PROVIDER = "provider", "Поставщик"
    
    name = models.CharField(verbose_name="Имя клиента", max_length=50)
    phone_number = models.CharField(verbose_name="Номер телефона", max_length=20)
    type = models.CharField(verbose_name="Тип клиента", max_length=20, choices=ContactType.choices, default=ContactType.CALL_ORDER)
    order = models.ForeignKey(Product, verbose_name="Продукт", on_delete=models.CASCADE, related_name="product_contacts", blank=True, null=True)
    datetime = models.DateTimeField(verbose_name="Дата и время", auto_now_add=True)

    class Meta:
        ordering = ("-id",)
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"
    
    def __str__(self) -> str:
        return f"{self.name} ({self.phone_number})" + (f" - {str(self.order)}" if self.order else "")

shop/forms.py
from django.contrib.admin.widgets import AdminTextInputWidget
from django.forms import (
    ModelForm,
    NumberInput,
    TextInput
)

from .models import (
    Contact,
    ProductColor
)


class ContactForm(ModelForm):

    class Meta:
        model = Contact
        exclude = (
            "type",
            "datetime"
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget = TextInput(attrs={'placeholder': "Ваше имя"})
        self.fields['phone_number'].widget = TextInput(attrs={'placeholder': "Номер телефона"})
        self.fields['order'].widget = NumberInput(attrs={'style': "display: none;"})


class ProductColorAdminForm(ModelForm):

    class Meta:
        model = ProductColor
        fields = "__all__"
        widgets = {
            'color': AdminTextInputWidget(attrs={'type': "color"})
        }

shop/views.py
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render
)
from math import ceil
from os import listdir

from .forms import ContactForm
from .models import (
    Category,
    LogoLayOn,
    News,
    Product
)
from .utils import get_context_data


def index(request):
    context_data = get_context_data()
    categories = context_data['categories']
    categories_for_index_page = [categories[i : i + 6] for i in range(0, len(categories), 6)]
    news = News.objects.all()[:3]
    sponsors = [f"img/sponsors/{item}" for item in listdir("static/img/sponsors")]
    brands = [f"img/brands/{item}" for item in listdir("static/img/brands")]
    return render(request, "shop/index.html", {
        **context_data,
        'categories_for_index_page': categories_for_index_page,
        'news': news,
        'sponsors': sponsors,
        'brands': brands
    })


def benedict(request):
    return render(request, "shop/benedict.html", {
        **get_context_data()
    })


def benetex(request):
    return render(request, "shop/benetex.html", {
        **get_context_data()
    })


def logo_lay_on(request):
    logo_lay_ons = LogoLayOn.objects.all()
    length = logo_lay_ons.count()
    logo_lay_ons = [logo_lay_ons[0 : ceil(length / 2)], logo_lay_ons[ceil(length / 2) : length]]
    return render(request, "shop/logo_lay_on.html", {
        **get_context_data(),
        'logo_lay_ons': logo_lay_ons
    })


def category_detail(request, slug):
    category: Category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category)
    return render(request, "shop/category.html", {
        **get_context_data(),
        'category': category,
        'products': category.products.all()
    })


def product_detail(request, slug):
    product: Product = get_object_or_404(Product, slug=slug)
    category: Category = product.category.first()
    return render(request, "shop/product.html", {
        **get_context_data(),
        'product': product,
        'category': category,
        'order_form': ContactForm(initial={'order': product.id})
    })


def news_detail(request, slug):
    new: News = get_object_or_404(News, slug=slug)
    news = News.objects.exclude(id=new.id)[:3]
    return render(request, "shop/news.html", {
        **get_context_data(),
        'new': new,
        'news': news
    })


def form(request, type):
    form = ContactForm(request.POST)
    contact = form.save(commit=False)
    contact.type = type
    contact.save()
    return redirect(request.META.get('HTTP_REFERER') or "shop:index")

templates/shop/benedict.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}Benedict{% endblock %}

{% block content %}
<div class="container">


    <div class="medium-content" id="medium-content">
        <a href="{% url 'shop:index' %}" class="top-links">Главная</a> /
        <a href="{% url 'shop:benedict' %}" class="top-un-links">Benedict</a>
        <br>
        <a href="javascript:void(0);" class="benedict-url">
            <img src="{% static 'img/benedict.png' %}" alt="">
        </a>
        <div class="benedict-content">
            <h2 class="starting-text">Benedict</h2> <br>
            <p class="starting-content">
                Новый год встретили, идет активная подготовка к 23 февраля и 8 марта! Атмосфера <br>
                праздника предвкушение новых выходных дней приносят с собой дополнительную <br> нагрузку на работе и
                режим “успеть все”.
            </p> <br>
            <p class="starting-content">
                В стрессовых условиях главное сохранять спокойствие! В этом поможет <br>
                своевременный перерыв на кофе, аффирмации и увлажнитель воздуха “Pebble”.
            </p> <br>
            <p class="starting-content">
                С наступлением отопительного сезона влажность падает до 30%. Это становится <br>
                причиной плохого самочувствия, рассеянного внимания и быстрой утомляемости.
            </p> <br>
            <p class="starting-content">
                “Pebble” буквально тот самый глоток свежего воздуха! Увлажнитель создаст <br>
                комфортные условия для работы в офисе и для спокойного отдыха дома.
            </p> <br>
            <p class="starting-content">
                Экодизайн, встроенная подсветка, компактный размер - совершенный <br>
                комбо-набор для любого интерьера и помещения. Площадь работы увлажнителя - <br>
                до 20 м2.
            </p> <br>
            <p class="starting-content">
                200 штук в наличии <br>
                “Pebble”- поможет пережить длительные холода без стресса!
            </p> <br>
        </div>
        <h2 class="production-text">
            Продукция
        </h2>

        <div class="view-cards">
            <img src="{% static 'img/view-production.png' %}" alt="View production card 1">
            <img src="{% static 'img/view-production.png' %}" alt="View production card 2">
            <img src="{% static 'img/view-production.png' %}" alt="View production card 3">
        </div>
        <button type="button" class="view-button">Посмотреть продукцию</button>
    </div>

    {% include 'layout/call.html' %}

</div>

{% endblock %}

templates/shop/benetex.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}Benetex{% endblock %}

{% block content %}
<div class="container">


    <div class="medium-content" id="medium-content">
        <a href="{% url 'shop:index' %}" class="top-links">Главная</a> /
        <a href="{% url 'shop:benetex' %}" class="top-un-links">Benetex</a>
        <br>
        <a href="javascript:void(0);" class="benedict-url">
            <img src="{% static 'img/benetex.png' %}" alt="">
        </a>
        <div class="benedict-content">
            <h2 class="starting-text">Benetex</h2> <br>
            <p class="starting-content">
                Новый год встретили, идет активная подготовка к 23 февраля и 8 марта! Атмосфера <br>
                праздника предвкушение новых выходных дней приносят с собой дополнительную <br> нагрузку на работе и
                режим
                “успеть все”.
            </p> <br>
            <p class="starting-content">
                В стрессовых условиях главное сохранять спокойствие! В этом поможет <br>
                своевременный перерыв на кофе, аффирмации и увлажнитель воздуха “Pebble”.
            </p> <br>
            <p class="starting-content">
                С наступлением отопительного сезона влажность падает до 30%. Это становится <br>
                причиной плохого самочувствия, рассеянного внимания и быстрой утомляемости.
            </p> <br>
            <p class="starting-content">
                “Pebble” буквально тот самый глоток свежего воздуха! Увлажнитель создаст <br>
                комфортные условия для работы в офисе и для спокойного отдыха дома.
            </p> <br>
            <p class="starting-content">
                Экодизайн, встроенная подсветка, компактный размер - совершенный <br>
                комбо-набор для любого интерьера и помещения. Площадь работы увлажнителя - <br>
                до 20 м2.
            </p> <br>
            <p class="starting-content">
                200 штук в наличии <br>
                “Pebble”- поможет пережить длительные холода без стресса!
            </p> <br>
        </div>
        <h2 class="production-text">
            Продукция
        </h2>

        <div class="view-cards">
            <img src="{% static 'img/view-production.png' %}" alt="View production card 1">
            <img src="{% static 'img/view-production.png' %}" alt="View production card 2">
            <img src="{% static 'img/view-production.png' %}" alt="View production card 3">
        </div>
        <button type="button" class="view-button">Посмотреть продукцию</button>
    </div>

    {% include 'layout/call.html' %}

</div>

{% endblock %}

templates/shop/category.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}{{ category }}{% endblock %}

{% block content %}
<div class="medium-content" id="medium-content">
    <a href="{% url 'shop:index' %}" class="top-links">Главная</a> /
    <a href="{% url 'shop:category' slug=category.slug %}" class="top-un-links">{{ category.name }}</a>
    <br>
    <!-- When mobile size is be active, this toggle is be active momentally -->
    <button onclick="myCatalogyDrop()" class="button-catalog">Выбрать категорию</button>
    <div class="catalog-tovarov">
        <div class="sidebar-menu" id="catalogy-tovarov">
            <div class="accordion">
                <h2 class="catalog-title">Категории</h2>
                <hr>
                {% for item in categories %}
                <div class="accordion-content">
                    <div class="header" {% if item.slug == category.parent_category.slug %}id="header"{% endif %}>
                        <span class="title">{{ item.name }}</span>
                        <i class="fa-solid fa-chevron-down"></i>
                    </div>
                    <ul class="description">
                        {% for sub_category in item.sub_categories.all %}
                        <li>
                            <a {% if category.slug != sub_category.slug %}href="{% url 'shop:category' slug=sub_category.slug %}"{% else %}id="defaultOpen"{% endif %} class="descript-link">
                                {{ sub_category.name }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="tovar-menu">
            <div id="biznesNabor" class="tovar-content">
                <h3 class="nabori-title">{{ category.name }}</h3>
                <div class="vid-tovara">
                    {% for product in products %}
                    <a href="{% url 'shop:product' slug=product.slug %}" class="tovar-list-url">
                        <div class="tovar-img">
                            <img src="{{ product.image.url }}" alt="{{ product.name }}">
                        </div>
                        <div class="tovar-opisanie">
                            <span class="name-of-tovar">{{ product.name }}</span>
                            <span class="price-of-tovar">от {{ product.price }}</span>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/category.js' %}"></script>
{% endblock %}

templates/shop/index.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}Landing Page{% endblock %}

{% block content %}
<div class="container">
    <!-- Home page banners -->
    <div class="content-of-sliders">
        <div id="slider">
            <div class="slide">
                <img
                    src="https://storage2.alifshop.uz/files?k1=7c5f595a-11fb-4923-8dde-f026422dd4d4&k2=9bfd1fb3102e47767d616d87c1505daede1060390aadd82711bcafa254d32dbef0fa1499ec7b5fd7d63c13ccb3cd5b4c0afa7e831f49af3aaca7aa78484bccf6">
            </div>

            <div class="slide">
                <img
                    src="https://storage2.alifshop.uz/files?k1=a3412866-19cc-4cee-a3d7-fbd37d2236bc&k2=231b0ce76fdc7f28869c455182864f04c212fbcdefb6f64df2add3a9391fc69b96c81fd1d8a47ed67fb3883fcb996707a464f6ab38a6b50a95431549bf69f036">
            </div>

            <div class="slide">
                <img
                    src="https://storage2.alifshop.uz/files?k1=b95308b1-1cf4-4404-8169-b335795b9027&k2=f0a20668b5e8d083a57b760a770c0773b79d21fd2366ff0e1cebc86e112081b9c5f398d996f526d587712bb606233e777b13b36ae7a58ab2f500fdc3cfe190a2">
            </div>

            <div class="slide">
                <img
                    src="https://storage2.alifshop.uz/files?k1=b813d38d-91fa-4a9b-932d-a6f65498328c&k2=9efc0e6fcea6cc877adf8408d3314ec38e75d75b0d0a8ae6bf4d927f9a510e5d4036c6384eb6d947f62ea18699a4ee056c86975958aac6f05537856b4aefb7cb">
            </div>

            <!--Controlling arrows-->
            <span class="controls" onclick="prevSlide(-1)" id="left-arrow"><i class="fa-solid fa-chevron-left"></i></i>
            </span>
            <span class="controls" id="right-arrow" onclick="nextSlide(1)"><i class="fa-solid fa-angle-right"></i>
            </span>
        </div>
        <div id="dots-con">
            <span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span>
        </div>
    </div>

    <!-- Products -->
    <div class="product-container" id="product-container">
        {% for collection in categories_for_index_page %}
        <div class="column-products">
            {% for item in collection %}
            <div class="product"
                onclick="window.location='{% if item.sub_category_first %}{% url 'shop:category' slug=item.sub_category_first.slug %}{% else %}javascript:void(0);{% endif %}'"
                style="cursor: pointer;">
                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="{{ item.slug }}">
                <span class="text">{{ item.name }}</span>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>

    <!-- When mobile size is be active, this toggle is be active momentally -->
    <button onclick="myCatalogyDrop()" class="button-catalogg">Выбрать категорию</button>

    <div class="ct-tovar">
        <div class="sidebar-menu" id="catalogy-tovarov">
            <div class="accordion">
                <h2 class="catalog-title">Категории</h2>
                <hr>
                {% for item in categories %}
                <div class="accordion-content">
                    <div class="header" {% if item.slug == 'nabor' %}id="header" {% endif %}>
                        <span class="title">{{ item.name }}</span>
                        <i class="fa-solid fa-chevron-down"></i>
                    </div>
                    <ul class="description">
                        {% for sub_category in item.sub_categories.all %}
                        <li>
                            <a href="{% url 'shop:category' slug=sub_category.slug %}" {% if item.slug == 'biznes-nabor' %}id="defaultOpen" class="descript-link" {% endif %}>
                                {{ sub_category.name }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% include 'layout/call.html' %}

    <!-- News section -->
    <h4 class="text-center">Новости</h4>

    <div class="medium-content" id="medium-content">

        <div class="news-section">
            {% for new in news %}
            <div class="card">
                <a href="{% url 'shop:news' slug=new.slug %}">
                    <img src="{{ new.image.url }}" alt="{{ new.name }}">
                </a>
                <div class="data-part">
                    <span class="data#">#новости</span>
                    <p class="data-number">{{ new.created_at | date:"d M Y" }}</p>
                </div>
                <h2>{{ new.name }}</h2>
                <p>{{ new.description }}</p>
            </div>
            {% endfor %}
        </div>

        <!-- About company section -->
        <div id="about">
            <h4 class="text-center-about">О компании</h4>
            <div class="about-company">
                <div class="mini-section">
                    <div class="include-part">
                        <h3>30 лет</h3>
                        <span>Работаем на рынке</span>
                    </div>
                </div>
                <br>
                <div class="mini-section">
                    <div class="include-part">
                        <h3>100 +</h3>
                        <span>Единиц оборудования</span>
                    </div>
                </div>
                <br>
                <div class="mini-section">
                    <div class="include-part">
                        <h3>100000 +</h3>
                        <span>Наменований товаров в каталогах</span>
                    </div>
                </div>
                <br>
                <div class="mini-section-last">
                    <div class="include-part-last">
                        <h3>1000000 +</h3>
                        <span>Товаров произведено на собственном производстве</span>
                    </div>
                </div>
                <br>
            </div>
        </div>




        <div class="buttonss">
            <button type="button" class="see-categories">Посмотреть каталоги</button>
            <button type="button" class="see-categories-1">Cкачать презентацию о нас</button>
        </div>

        <h4 class="text-center-about">
            Нам доверяют</h4>
        <!-- Нам доверют section -->
        <div class="slider-logo">
            <div class="slide-track">
                {% for sponsor in sponsors %}
                <div class="slide-logo">
                    <img src="{% static sponsor %}" alt="">
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Our brands section -->
        <h4 class="text-center-about" id="ourBrands">Наши бренды</h4>
        <div class="carousel" data-flickity='{ "lazyLoad": true }'>
            {% for brand in brands %}
            <div class="carousel-cell">
                <img class="carousel-cell-image" data-flickity-lazyload="{% static brand %}" alt="tulip" />
            </div>
            {% endfor %}
        </div>
        <!-- Our Location -->
        <h4 class="text-center-about" id="ourLocation">Наша локация</h4>
        <div class="location-section">
            <form method="POST" action="{% url 'shop:form' type='call-order' %}">
                <div class="form-content">
                    <p class="form-text">Появились вопросы? <br>Закажите звонок</p>
                    {% csrf_token %}
                    {{ contact_form.name }}
                    {{ contact_form.phone_number }}
                    <button type="submit" class="send">Заказать звонок</button>
                </div>
            </form>
            <div class="map-content">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7609.302803850238!2d69.26637182430865!3d41.299585420295685!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8b4c09937635%3A0xd13469e31301fd8c!2sBenegifts!5e0!3m2!1sen!2s!4v1678612514248!5m2!1sen!2s"
                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>


</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

templates/shop/news.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}{{ new.name }}{% endblock %}

{% block content %}
<div class="medium-content" id="medium-content">
    <a href="{% url 'shop:index' %}" class="top-links">Главная</a> /
    <a href="{% url 'shop:index' %}#medium-content" class="top-links">Новости</a> /
    <a href="{% url 'shop:news' slug=new.slug %}" class="top-un-links">{{ new.name }}</a>
    <br>
    <div class="benedict-content">
        <h2 class="starting-text">{{ new.name }}</h2> <br>
        {{ new.content | safe }}
        <img src="{{ new.image.url }}" class="news-item-image" alt="{{ new.name }}">
    </div>
    {% if news %}
        <h4 class="text-center">Другие новости</h4>
        <div class="news-section" id="news-items">
            {% for item in news %}
            <div class="card">
                <a href="{% url 'shop:news' slug=item.slug %}">
                    <img src="{{ item.image.url }}" alt="{{ item.name }}">
                </a>
                <div class="data-part">
                    <span class="data#">#новости</span>
                    <p class="data-number">{{ item.created_at | date:"d M Y" }}</p>
                </div>
                <h2>{{ item.name }}</h2>
                <p>{{ item.description }}</p>
            </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

templates/shop/product.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="medium-content" id="medium-content">
    <a href="{% url 'shop:index' %}" class="top-links">Главная</a> /
    <a href="{% url 'shop:category' slug=category.slug %}" class="top-links">{{ category.name }}</a> /
    <a href="{% url 'shop:product' slug=product.slug %}" class="top-un-links">{{ product.name }}</a>
    <!-- part of product image and description, color, size, weight -->
    <div class="into-product">
        <div class="product-into-images">
            <img src="{{ product.image.url }}" class="main-img" alt="{{ product.name }}">
            <div class="three-part-images">
                {% for product_image in product.product_images.all %}
                <img src="{{ product_image.image.url }}" alt="{{ product.name }}">
                {% endfor %}
            </div>
        </div>
        <div class="product-into-sizes">
            <strong>{{ product.name }}</strong>
            <div class="common-product-ch">
                <div class="size-of-product">
                    <span>РАЗМЕРЫ</span>
                    <p>{{ product.size }}</p> <br>
                    <span>МАТЕРИАЛ</span>
                    <p>{{ product.material }}</p> <br>
                    <span>ВЕС: {{ product.weight }}</span>
                </div>
                <div class="color-picker-pr">
                    <p class="title-colorlist">
                        Цвета в наличии
                    </p>
                    {% for product_colors in product.product_colors_by_three %}
                    <div class="colorList">
                        {% for product_color in product_colors %}
                        <button style="background-color: {{ product_color.color }};"></button>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <hr>
            <br>
            <span class="from-price">От <strong>{{ product.price }}</strong></span>
            <br>
            <br>
            <button class="ordering" id="zakaz-button">Заказать</button>
        </div>
    </div>
    <div class="ending-description">
        <strong>Описание</strong>
        {{ product.description | safe }}
    </div>
    <div id="myZakazModal" class="modalZakaz">
        <form method="POST" action="{% url 'shop:form' type='product-order' %}">
            <!-- Modal content -->
            <div class="modal-content-zakaz">
                <div class="modal-header">
                    <p class="form-text-zakaz">Оформление заявки <br>
                        на приобретение <br>
                        товара</p>
                    <span class="close-zakaz">&times;</span>
                </div>
                {% csrf_token %}
                {{ order_form.name }}
                {{ order_form.phone_number }}
                {{ order_form.order }}
                <button type="submit" class="send">Заказать звонок</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/product.js' %}"></script>
<script>

</script>
{% endblock %}