benegifts/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    include,
    path
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop import views

app_name = "shop"


urlpatterns = [
    path("", views.index, name="index"),
    path("benedict/", views.benedict, name="benedict"),
    path("benetex/", views.benetex, name="benetex"),
    path("logo-lay-on/", views.logo_lay_on, name="logo_lay_on"),
    path("category/<slug:slug>/", views.category_detail, name="category"),
    path("product/<slug:slug>/", views.product_detail, name="product"),
    path("news/<slug:slug>/", views.news_detail, name="news"),
    path("form/<str:type>/", views.form, name="form"),
]

templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'icon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon/apple-touch-icon.png' %}">
    <link rel="icon" href="{% static 'icon/favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="icon" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% static 'icon/android-chrome-192x192.png' %}" sizes="192x192" type="image/png">
    <link rel="icon" href="{% static 'icon/android-chrome-512x512.png' %}" sizes="512x512" type="image/png">
    <title>Benegifts - {% block title %}{% endblock %}</title>
    <!-- Style css connect -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Button categories css -->
    <link rel="stylesheet" href="{% static 'css/button.css' %}">
    <!-- Media query -->
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <!-- Flicky -->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="container">
        <!-- Header section -->
        {% include 'layout/navbar.html' %}
        {% include 'layout/header.html' %}
        {% block content %}{% endblock %}
        {% include 'layout/footer.html' %}
        {% include 'layout/modals.html' %}
    </div>
    <!-- Button categories -->
    <script src="{% static 'js/toggle-menu.js' %}"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block script %}{% endblock %}
</body>

</html>

templates/layout/call.html
<!-- Заказать звонок section -->
<div class="call-section-1" id="call-section">
    <form method="POST" action="{% url 'shop:form' type='call-order' %}" class="forma-otpravki">
        {% csrf_token %}
        {{ contact_form.name }}
        
        {{ contact_form.phone_number }}
        <button type="submit" class="send">Заказать звонок</button>
    </form>
</div>

templates/layout/footer.html
<!-- footer section -->
<footer id="footer">
    <div class="content">
        <div class="link-boxes">
            <ul class="box">
                <!-- <li class="link_name">Документы</li> -->
                <li><a href="{% url 'shop:index' %}#about">О компании</a></li>
                <li><a href="{% url 'shop:benedict' %}">Benedict</a></li>
                <li><a href="{% url 'shop:benetex' %}">Benetex</a></li>
                <li><a href="{% url 'shop:logo_lay_on' %}">Нанесение логотипа</a></li>
            </ul>
            <ul class="box">
                <!-- <li class="link_name">Сервис</li> -->
                <li><a href="{% url 'shop:index' %}#product-container">Категории</a></li>
                <li><a href="{% url 'shop:index' %}#medium-content">Новости</a></li>
                <li><a href="{% url 'shop:index' %}#ourBrands">Наши бренды</a></li>
                <li><a href="{% url 'shop:index' %}#ourLocation">Наша локация</a></li>
            </ul>
            <ul class="box">
                <!-- <li class="link_name">Каталог товаров</li> -->
                <li><a href="javascript:void(0);">Презентация о нас</a></li>
                <li><a href="javascript:void(0);">Посмотреть каталоги</a></li>
            </ul>
            <ul class="box input-box">
                <li class="link_name">Мы в соц-медиа</li>
                <div class="media-icons">
                    <a href="https://t.me/benegifts">
                        <i class="fab fab fa-telegram"></i>
                    </a>
                    <a href="https://instagram.com/benegifts.uz?igshid=YmMyMTA2M2Y">
                        <i class="fab fa-instagram"></i>
                    </a>
                </div>
                <li><a href="javascript:void(0);">@benegifts_uz</a></li>
                <li><a href="tel:+998990032244">+998 99 003 22 44</a></li>
                <li><a href="tel:+998990032244">+998 99 003 22 44</a></li>
            </ul>
        </div>
    </div>
    <hr class="line">
    <div class="bottom-details">
        <div class="bottom_text">
            <span class="copyright_text">2023 © benegifts.uz</span>
        </div>
    </div>
</footer>

templates/layout/header.html
{% load static %}

<!-- header Logo  -->
<div class="row">
    <div id="mySidepanel" class="sidepanel">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">
            <i class="fa-solid fa-xmark"></i>
        </a>
        <ul>
            <li>
                <a href="{% url 'shop:index' %}#about" class="linkk">О компании</a>
            </li>
            <li>
                <a href="{% url 'shop:benedict' %}" class="linkk">Benedict</a>
            </li>
            <li>
                <a href="{% url 'shop:benetex' %}" class="linkk">Benetex</a>
            </li>
            <li>
                <a href="{% url 'shop:logo_lay_on' %}" class="linkk">Нанесение логотипа</a>
            </li>
            <li>
                <a href="https://drive.google.com/drive/folders/1gBGuvnNYMybjlfhV9qSATJug81gzpv0T" class="linkk">Cкачать
                    каталоги</a>
            </li>
        </ul>
    </div>
    <div class="col-logo">
        <a href="{% url 'shop:index' %}">
            <img src="{% static 'img/benegifts-logo.svg' %}" alt="Benegifts">
        </a>
        <button class="openbtn" id="openbtn" onclick="openNav()">
            <i class="fa-solid fa-bars-progress"></i>
        </button>
    </div>
    <div class="col-input">
        <button type="button" class="category-button" onclick="myFunction()">
            <i class="fa-solid fa-bars" id="icon1"></i>
            <span>Категории товаров</span>
        </button>
        <!-- After clicking button happens -->
        <div id="myDropdown" class="dropdown-content">
            <div class="drop-container">
                <div class="tab">
                    {% for item in categories %}
                    <button class="tablinks" onmouseover="openCity(event, '{{ item.slug }}')">{{ item.name }}</button>
                    {% endfor %}
                </div>
                {% for key, sub_categories_collection in sub_categories_dict.items %}
                <div id="{{ key }}" class="tabcontent">
                    <div class="section-1">
                        {% for sub_categories in sub_categories_collection %}
                        <ul>
                            {% for sub_category in sub_categories %}
                            <li>
                                <a href="{% url 'shop:category' slug=sub_category.slug %}">{{ sub_category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- search bar -->
        <input type="search" name="searchInput" placeholder="Искать товары" autocomplete="off" class="form-control">
        <button type="button" class="search-button">
            <i class="fa-solid fa-magnifying-glass"></i>
        </button>
    </div>
    <div class="col-number">
        <a href="tel:+998990032244" class="phone-number">+998 99 003 22 44</a>
        <a href="tel:+998990032244" class="phone-number">+998 99 003 22 44</a>
    </div>
</div>

<!-- Vertical Tab Links for dileram && Postavshikam -->
<div class="dileram-postavshikam">
    <a href="javascript:void(0)" class="vertical-tab-links" id="myBtnVertical">Дилерам</a>
    <a href="javascript:void(0)" class="vertical-tab-links" id="my2BtnVertical">Поставщикам</a>
</div>

templates/layout/modals.html
<!-- popUp form -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <form method="POST" action="{% url 'shop:form' type='dealer' %}">
        <div class="modal-content">
            <div class="modal-header">
                <p class="form-text">Форма обратной <br> связи для дилеров</p>
                <span class="close">&times;</span>
            </div>
            {% csrf_token %}
            {{ contact_form.name }}
            {{ contact_form.phone_number }}
            <button type="submit" class="send">Заказать звонок</button>
        </div>
    </form>

</div>

<!-- PopUp for postavshikov -->
<div id="my2Modal" class="modal2">

    <!-- Modal content -->
    <form method="POST" action="{% url 'shop:form' type='provider' %}">
        <div class="modal-content2">
            <div class="modal-header2">
                <p class="form-text2">Форма обратной <br> связи для <br> поставщиков</p>
                <span class="close2">&times;</span>
            </div>
            {% csrf_token %}
            {{ contact_form.name }}
            {{ contact_form.phone_number }}
            <button type="submit" class="send">Заказать звонок</button>
        </div>
    </form>

</div>

templates/layout/navbar.html
<!-- navbar links section -->
<div class="navlinks">
    <ul>
        <li>
            <a href="{% url 'shop:index' %}#about" class="linkk">
                О компании
            </a>
        </li>
        <li>
            <a href="{% url 'shop:benedict' %}" class="linkk">
                Benedict
            </a>
        </li>
        <li>
            <a href="{% url 'shop:benetex' %}" class="linkk">
                Benetex
            </a>
        </li>
        <li>
            <a href="{% url 'shop:logo_lay_on' %}" class="linkk">
                Нанесение логотипа
            </a>
        </li>
        <li>
            <a href="javascript:void(0)" class="linkk" id="myBtn">
                Дилерам
            </a>
        </li>
        <li>
            <a href="javascript:void(0)" class="linkk" id="my2Btn">
                Поставщикам
            </a>
        </li>
        <li>
            <a href="https://drive.google.com/drive/folders/1gBGuvnNYMybjlfhV9qSATJug81gzpv0T" class="linkk">
                Cкачать каталоги
            </a>
        </li>
    </ul>
</div>